#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    # Remove debconf data
    if [ -e /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
        db_purge || true
    fi
fi

#DEBHELPER#
